version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "powermgr-prod"
s3_prefix = "powermgr-prod"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"prod\""
image_repositories = []

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "powermgr-dev"
s3_prefix = "powermgr-dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""

[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "powermgr-staging"
s3_prefix = "powermgr-staging"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"staging\""
